# Site settings
author: David s. Little
title: ruby project
header-img: img/home-bg.png
email: littledavid175@gmail.com
copyright_name: David s. Little
description: > # this means to ignore newlines until "baseurl:"
  learning about failure
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wizardywizard

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
